export const indianCities = [
  'Agra',
  'Ahmedabad',
  'Amritsar',
  'Bangalore',
  'Bhopal',
  'Bhubaneswar',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Delhi',
  'Goa',
  'Guwahati',
  'Hyderabad',
  'Indore',
  'Jaipur',
  'Jodhpur',
  'Kochi',
  'Kolkata',
  'Lucknow',
  'Mumbai',
  'Mysore',
  'Nagpur',
  'Pune',
  'Raipur',
  'Ranchi',
  'Surat',
  'Thiruvananthapuram',
  'Udaipur',
  'Varanasi',
  'Visakhapatnam'
] as const;

export type IndianCity = typeof indianCities[number]; 